# Generated by Django 6.1 on 2026-09-02 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_allowed",
        ),
    ]
