# Generated by Django 6.1 on 2026-09-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_poi'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='strava_activity_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
