# Generated by Django 6.1 on 2026-09-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_activity_strava_activity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='sport_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
