# Generated by Django 6.1 on 2026-09-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_activity_sport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='distance_m',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
