# Generated by Django 6.1 on 2026-09-17 14:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_activity_distance_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='track',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
